name: flutter_tailwind_css_colors
description: A pure Dart implementation around Tailwind CSS colors framework.
version: 0.1.1
repository: https://github.com/Xeertz-Org/flutter_tailwind_css_colors

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
