name: flutter_tailwind_colors
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/Xeertz-Org/flutter_tailwind_colors

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
