name: flutter_tailwind_css_colors
description: A pure Dart implementation around Tailwind CSS colors.
version: 0.0.2
repository: https://github.com/Xeertz-Org/flutter_tailwind_css_colors

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
      sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
